### ISSUE TITLE
Added to minification-benchmarks

### ISSUE THREAD

**Issue by privatenumber** [wilsonzlin/minify-js#10]
Hey, just wanted to give you a heads up that we started benchmarking your minifier here:
https://github.com/privatenumber/minification-benchmarks

Thanks for your project and good luck!

**Comment by wilsonzlin** [comment]
That sounds great, excited to be part of the benchmarks!

I did some work on the parser and minifier over the last week, which should have some impact on the performance and effectiveness. Do the benchmarks automatically re-run on a new version? I released a new minor version `0.5.1`, which is technically breaking, but there's no change in the Node.js API, only the Rust API.

**Comment by privatenumber** [comment]
Yeah any new version published to npm should trigger [Renovate](https://github.com/renovatebot/renovate) to open a new PR and automatically benchmark it.
