### ISSUE TITLE
add a background to the graphs in the readme

### ISSUE THREAD

**Issue by SArpnt** [wilsonzlin/minify-js#2]
with github dark theme, it's nearly impossible to see that there's any text
![image](https://user-images.githubusercontent.com/36542932/181373210-455af3d8-bf91-4108-ae3b-70ee2eef286f.png)
adding a background to the image would fix this

**Comment by wilsonzlin** [comment]
Done, thanks for raising, the next render will have a white background.

**Comment by Rongronggg9** [comment]
Uh-huh 🤔

![](https://user-images.githubusercontent.com/15956627/203208434-f7f3f74c-db2d-4834-a24a-0c7063f910ad.png)
