### ISSUE TITLE
Crash on parsing private methods

### ISSUE THREAD

**Issue by KacperZielinski-Intel** [wilsonzlin/minify-js#3]
This minimal code:
```js
class Foo {
   #Bar() {
      console.log("Compress me!");
   }
}
```

outputs this error:
`thread 'main' panicked at 'minify: Syntax(ExpectedNotFound [position=16 token=None] around ```class Foo {
    #Bar() {
        console.log("Compress m```)', cli\src\main.rs:33:41`

**Comment by wilsonzlin** [comment]
Thanks for raising, I've just implemented support for private member fields and accesses in `0.2.4`, let me know if it works for your code.
