### ISSUE TITLE
Feature Request : macro to embed js inside binaries

### ISSUE THREAD

**Issue by felipetesc** [wilsonzlin/minify-js#6]
Nice lib. 

I would like to suggest the addition of a new feature: 

What about creating a macro, such as minify!(...), so we can embed js inside the binaries. With this feature we will be able to use it with projects such as Tauri, and web servers. 

It could use something like include_bytes!, and include_str!. 

Thanks.

**Comment by wilsonzlin** [comment]
That's a common use case, and I'd suggest using something like `lazy_static`:

```rust
lazy_static::lazy_static! {
  pub static ref JS: Vec<u8> = {
    let mut out = Vec::new();
    minify_js::minify(minify_js::TopLevelMode::Global, include_bytes!("./index.js"), &mut out).unwrap();
    out
  };
}
```

The minification is too complex, so it can't be done as a const function (or macro) and executed at compile time using the compiler, however a workflow could be possible using `build.rs`. I'd be interested in looking into it.
