### ISSUE TITLE
fails to minify lambda with parenthesis

### ISSUE THREAD

**Issue by florentbr** [wilsonzlin/minify-js#8]
The algorithm is removing the parenthesis on lambda expressions. It breaks the code in some cases.

For instance :

` let fns = [ x => (1, 2)  ] `

is compressed as 

`let fns = [ x => 1,  2  ]`
 
The original code creates an array with a single function returning `2`.
The compressed code creates an array with a lambda returning `1` and with an additional entry `2`.

**Comment by wilsonzlin** [comment]
Thanks for raising, I've just fixed this in the latest version `0.4.3`, let me know if it works on your end.

**Comment by florentbr** [comment]
Thanks, I'll let you know once it lands on minify-html pypi.
